name: Daily Node.js Script

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify your Node.js version here
      
    - name: Install dependencies
      run: npm install
      
    - name: Run Node.js script
      run: node Tender_Selesai.js  # Replace with the path to your script
      env:
        GOOGLE_SHEET_KEY_JSON: ${{ secrets.GOOGLE_SHEET_KEY_JSON }}
        API_URL_TS: ${{ secrets.API_URL_TS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
